config/routes.rb
Expense::Application.routes.draw do

  resources :manage_expenses

  resources :users

  devise_for :groups

  root :to => 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :group_name, :description
  # attr_accessible :title, :body
  has_many :users
  has_many :manage_expenses
end

app/models/manage_expense.rb
class ManageExpense < ActiveRecord::Base
  attr_accessible :description, :divide_among, :people_paid, :title, :total_amount
  attr_accessible :group_id, :per_head
  belongs_to :group
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :phone_number, :group_id
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/manage_expenses_controller.rb
class ManageExpensesController < ApplicationController
  # GET /manage_expenses
  # GET /manage_expenses.json
  def index
    @manage_expenses = ManageExpense.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @manage_expenses }
    end
  end

  # GET /manage_expenses/1
  # GET /manage_expenses/1.json
  def show
    @manage_expense = ManageExpense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manage_expense }
    end
  end

  # GET /manage_expenses/new
  # GET /manage_expenses/new.json
  def new
    @manage_expense = ManageExpense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manage_expense }
    end
  end

  # GET /manage_expenses/1/edit
  def edit
    @manage_expense = ManageExpense.find(params[:id])
  end

  # POST /manage_expenses
  # POST /manage_expenses.json
  def create
    @manage_expense = ManageExpense.new(params[:manage_expense])

    respond_to do |format|
      if @manage_expense.save
        format.html { redirect_to @manage_expense, notice: 'Manage expense was successfully created.' }
        format.json { render json: @manage_expense, status: :created, location: @manage_expense }
      else
        format.html { render action: "new" }
        format.json { render json: @manage_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /manage_expenses/1
  # PUT /manage_expenses/1.json
  def update
    @manage_expense = ManageExpense.find(params[:id])

    respond_to do |format|
      if @manage_expense.update_attributes(params[:manage_expense])
        format.html { redirect_to @manage_expense, notice: 'Manage expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manage_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manage_expenses/1
  # DELETE /manage_expenses/1.json
  def destroy
    @manage_expense = ManageExpense.find(params[:id])
    @manage_expense.destroy

    respond_to do |format|
      format.html { redirect_to manage_expenses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manage_expenses_helper.rb
module ManageExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expense</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/manage_expenses/_form.html.erb
<%= form_for(@manage_expense) do |f| %>
  <% if @manage_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manage_expense.errors.count, "error") %> prohibited this manage_expense from being saved:</h2>

      <ul>
      <% @manage_expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :total_amount %><br />
    <%= f.number_field :total_amount %>
  </div>
  <div class="field">
    <%= f.label :divide_among %><br />
    <%= f.number_field :divide_among %>
  </div>
  <div class="field">
    <%= f.label :people_paid %><br />
    <%= f.number_field :people_paid %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manage_expenses/edit.html.erb
<h1>Editing manage_expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @manage_expense %> |
<%= link_to 'Back', manage_expenses_path %>

app/views/manage_expenses/index.html.erb
<h1>Listing manage_expenses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Total amount</th>
    <th>Divide among</th>
    <th>People paid</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @manage_expenses.each do |manage_expense| %>
  <tr>
    <td><%= manage_expense.title %></td>
    <td><%= manage_expense.total_amount %></td>
    <td><%= manage_expense.divide_among %></td>
    <td><%= manage_expense.people_paid %></td>
    <td><%= manage_expense.description %></td>
    <td><%= link_to 'Show', manage_expense %></td>
    <td><%= link_to 'Edit', edit_manage_expense_path(manage_expense) %></td>
    <td><%= link_to 'Destroy', manage_expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Manage expense', new_manage_expense_path %>

app/views/manage_expenses/new.html.erb
<h1>New manage_expense</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_expenses_path %>

app/views/manage_expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @manage_expense.title %>
</p>

<p>
  <b>Total amount:</b>
  <%= @manage_expense.total_amount %>
</p>

<p>
  <b>Divide among:</b>
  <%= @manage_expense.divide_among %>
</p>

<p>
  <b>People paid:</b>
  <%= @manage_expense.people_paid %>
</p>

<p>
  <b>Description:</b>
  <%= @manage_expense.description %>
</p>


<%= link_to 'Edit', edit_manage_expense_path(@manage_expense) %> |
<%= link_to 'Back', manage_expenses_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.phone_number %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Phone number:</b>
  <%= @user.phone_number %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>